version: '3.2'
services:
  polls:
    image: polls
    container_name: polls
    hostname: polls
    build:
      context: .
      args:
        DB_NAME: tibero
        DB_HOST: tibero6
        DB_PORT: 8629
    ports:
      - "8000:8000"
    networks:
      - docker_tibero_default
networks:
  docker_tibero_default:
    external: true
